[storage]
storagetype = "local"

[upload]
verification = true

[download]
verification = false

[db]
dbtype = "mongo"
dbname = "faceRecDB"
embedding_table = "img2emb"
config_table = "configs"
events_table = "events"

[algo]
algo_name = "faiss"  #faiss+mongo
index_name = "IndexFlatL2"
embedding_dimensions = 512